### ISSUE TITLE
Request for Requirements File for Text2TTP

### ISSUE THREAD

**Issue by uppp** [qcri/Text2TTP#1]
Hi Lekssays,

I hope this message finds you well. I am very interested in your Text2TTP on GitHub and would like to replicate it on my local machine. However, I noticed that the repository does not include a requirements file listing the necessary dependencies. 

Could you please provide a `requirements.txt` file or a list of the required packages?

Thank you very much for your assistance.

Best regards,
Emily Watson

**Comment by Lekssays** [comment]
Hi there!

We provide a conda environment.yml file where you can file all the dependencies. In addition, you can find our models on HF:  [https://huggingface.co/collections/qcri-cs/text2ttp-6648e136db255eefa7456d96](https://huggingface.co/collections/qcri-cs/text2ttp-6648e136db255eefa7456d96).

If you need further assistance please let us know.

**Comment by uppp** [comment]
> Hi there!
> 
> We provide a conda environment.yml file where you can file all the dependencies. In addition, you can find our models on HF: https://huggingface.co/collections/qcri-cs/text2ttp-6648e136db255eefa7456d96.
> 
> If you need further assistance please let us know.

Hi there！
Thank you very much for your reply.
The issue I am facing is the compatibility issue between the versions of Transformers and Sense Transformers. I would like to know the versions of these two dependency packages, but their versions are not provided in Conda Environment.yml.And,the link on HF cannot be opened.

**Comment by Lekssays** [comment]
```

```

> > Hi there!
> > We provide a conda environment.yml file where you can file all the dependencies. In addition, you can find our models on HF: https://huggingface.co/collections/qcri-cs/text2ttp-6648e136db255eefa7456d96.
> > If you need further assistance please let us know.
> 
> Hi there！ Thank you very much for your reply. The issue I am facing is the compatibility issue between the versions of Transformers and Sense Transformers. I would like to know the versions of these two dependency packages, but their versions are not provided in Conda Environment.yml.And,the link on HF cannot be opened.

transformers              4.40.2                   pypi_0    pypi
sentence-transformers     2.7.0                    pypi_0    pypi
